import type { PlannedSession, PlannedWorkout } from '@/domain/entities';
import { formatDurationRange } from '@/lib/formatting';
import type { SessionVolumeAnalysis } from '@/services/volumeAnalyzer';

import type { RotationDurationPort, RotationVolumePort, SessionRotationPort } from './ports';
export interface NextSessionSuggestion { workout: PlannedWorkout; session: PlannedSession; sessionIndex: number; totalSessions: number; lastCompletedDate?: Date; }
export interface NextSessionSuggestionDetail extends NextSessionSuggestion { volume: SessionVolumeAnalysis; equipment: string[]; exerciseCount: number; totalSetsMin: number; totalSetsMax: number; durationLabel: string | null; }
export class SessionRotationUseCases {
  constructor(private readonly rotation: SessionRotationPort, private readonly volumes: RotationVolumePort, private readonly durations: RotationDurationPort, private readonly translate: (key: string) => string) {}
  async getNextSessionSuggestion(): Promise<NextSessionSuggestion | null> { const workouts = await this.rotation.getActiveWorkouts(); if (!workouts.length) return null; const workout = workouts[0]; const sessions = await this.rotation.getSessionsByWorkout(workout.id); sessions.sort((a, b) => a.orderIndex - b.orderIndex); if (!sessions.length) return null; const last = await this.rotation.getLatestCompletedSessionByWorkout(workout.id); if (!last) return { workout, session: sessions[0], sessionIndex: 0, totalSessions: sessions.length }; const lastIndex = sessions.findIndex(session => session.id === last.plannedSessionId); const sessionIndex = lastIndex === -1 ? 0 : (lastIndex + 1) % sessions.length; return { workout, session: sessions[sessionIndex], sessionIndex, totalSessions: sessions.length, lastCompletedDate: last.completedAt }; }
  async getNextSessionSuggestionDetail(): Promise<NextSessionSuggestionDetail | null> { const suggestion = await this.getNextSessionSuggestion(); if (!suggestion) return null; const volume = await this.volumes.analyzeSessionVolume(suggestion.session.id, suggestion.session.name, key => this.translate(`enums.muscle.${key}`), key => this.translate(`enums.muscleGroup.${key}`), key => this.translate(`enums.movementPattern.${key}`), undefined, true); const groups = await this.rotation.getGroups(suggestion.session.id); const items = await this.rotation.getItems(groups.map(group => group.id)); const exerciseIds = [...new Set(items.map(item => item.exerciseId))]; const exercises = await this.rotation.getExercises(exerciseIds); const equipment = [...new Set(exercises.flatMap(exercise => Array.isArray(exercise.equipment) ? exercise.equipment : [exercise.equipment]))].map(value => this.translate(`enums.equipment.${value}`)); const sets = await this.rotation.getSets(items.map(item => item.id)); const totalSetsMin = sets.reduce((total, set) => total + set.setCountRange.min, 0); const totalSetsMax = sets.reduce((total, set) => total + (set.setCountRange.max ?? set.setCountRange.min), 0); const duration = await this.durations.estimateSessionDuration(suggestion.session.id); return { ...suggestion, volume, equipment, exerciseCount: exerciseIds.length, totalSetsMin, totalSetsMax, durationLabel: duration.maxSeconds > 0 ? formatDurationRange(duration) : null }; }
}
